#if !canImport(ObjectiveC)
import XCTest

extension ChunkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChunkTests = [
        ("testAccess", testAccess),
        ("testEraseBlock", testEraseBlock),
        ("testGeometry", testGeometry),
        ("testNeighbours", testNeighbours),
        ("testReplace", testReplace),
    ]
}

extension GeometryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GeometryTests = [
        ("testBuildPath", testBuildPath),
        ("testPath", testPath),
        ("testTraverse", testTraverse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ChunkTests.__allTests__ChunkTests),
        testCase(GeometryTests.__allTests__GeometryTests),
    ]
}
#endif
