#if !canImport(ObjectiveC)
import XCTest

extension RengaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RengaTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(RengaTests.__allTests__RengaTests),
    ]
}
#endif
