#if !canImport(ObjectiveC)
import XCTest

extension GeometryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GeometryTests = [
        ("testBuildPath", testBuildPath),
        ("testPath", testPath),
        ("testTraverse", testTraverse),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GeometryTests.__allTests__GeometryTests),
    ]
}
#endif
